<div>
    <h1> create </h1>
    <form action="">
        <input type="text">
    </form>
    <h2>text</h2>
    <p>
        <?php
        /* Using magic getsetters */
        // echo $this->getSampleText();
        ?>
    </p>
    <p>
        <strong>
            <?php
            /* retrieving sample cfg value */
            //  echo $this->getCfgSample();
            ?>
        </strong>
    </p>
</div>
